[1499697110.352405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '0' for key 'PRIMARY'")
[1499697110.717405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697110.8304052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697110.970405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697112.363405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697112.5224051]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '1' for key 'PRIMARY'")
[1499697113.204405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697114.059405]: 
            MaxCost7_8Calculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697114.192405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time7_8costs' at row 1")
[1499697114.2464051]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '8' for key 'PRIMARY'")
[1499697114.9634051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697115.681405]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697115.6864052]: 
            MaxCost7_8Calculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697115.7584052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697115.772405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time7_8costs' at row 1")
[1499697115.820405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '9' for key 'PRIMARY'")
[1499697116.234405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_superMarket' at row 1")
[1499697116.408405]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_supermarket' at row 1")
[1499697116.484405]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_times_day_supermarket' at row 1")
[1499697116.494405]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_times_day_supermarket' at row 1")
[1499697117.0454051]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697117.312405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '10' for key 'PRIMARY'")
[1499697117.936405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697118.912405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '11' for key 'PRIMARY'")
[1499697119.536405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697120.154405]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697120.243405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697120.3614051]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '19' for key 'PRIMARY'")
[1499697120.6894052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697120.773405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697120.944405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697121.780405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697121.862405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '20' for key 'PRIMARY'")
[1499697122.5524049]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697123.503405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '21' for key 'PRIMARY'")
[1499697123.788405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697123.892405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697124.010405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697124.996405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697125.095405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '22' for key 'PRIMARY'")
[1499697125.819405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697126.927405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '23' for key 'PRIMARY'")
[1499697127.8934052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697128.704405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697128.844405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '28' for key 'PRIMARY'")
[1499697129.8184052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697131.194405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '29' for key 'PRIMARY'")
[1499697132.044405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697133.0554051]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697133.144405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '36' for key 'PRIMARY'")
[1499697134.176405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697135.810405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '37' for key 'PRIMARY'")
[1499697136.826405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697137.7294052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697137.827405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '56' for key 'PRIMARY'")
[1499697138.253405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697138.3374052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697138.5254052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697139.2774053]: 
            MaxCost7_8Calculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697139.3854053]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697139.388405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time7_8costs' at row 1")
[1499697139.435405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '57' for key 'PRIMARY'")
[1499697140.1014051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697141.0184052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697141.0934052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '62' for key 'PRIMARY'")
[1499697142.5344052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697143.424405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697143.5014052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '63' for key 'PRIMARY'")
[1499697143.504405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'avgdayscosts' at row 1")
[1499697143.5054052]: 
            BalanceRankCalculater
        	<class 'TypeError'>:unsupported operand type(s) for +: 'NoneType' and 'NoneType'
[1499697143.508405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cardrecharge' at row 1")
[1499697143.5424051]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_amount' at row 1")
[1499697143.544405]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_dinnerHall' at row 1")
[1499697143.546405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697143.548405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_superMarket' at row 1")
[1499697143.550405]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_dinnerhall' at row 1")
[1499697143.5524049]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697143.5544052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_supermarket' at row 1")
[1499697143.556405]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_times_day_dinnerhall' at row 1")
[1499697143.5574052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_times_day_supermarket' at row 1")
[1499697143.559405]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_times_day_supermarket' at row 1")
[1499697143.562405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_variance' at row 1")
[1499697144.0784051]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697144.079405]: 
            MaxCost7_8Calculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697144.1174052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697144.1174052]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time7_8costs' at row 1")
[1499697144.118405]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'totaldinnercosts' at row 1")
[1499697144.119405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '64' for key 'PRIMARY'")
[1499697145.291405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697146.6014051]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '65' for key 'PRIMARY'")
[1499697146.856405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cardrecharge' at row 1")
[1499697147.4174051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697148.458405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '66' for key 'PRIMARY'")
[1499697149.4664052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697150.751405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '67' for key 'PRIMARY'")
[1499697151.335405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697151.520405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697151.6834052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697153.1334052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '70' for key 'PRIMARY'")
[1499697153.8574052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697154.9064052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697155.0584052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '71' for key 'PRIMARY'")
[1499697155.799405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697156.661405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697156.808405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '74' for key 'PRIMARY'")
[1499697157.848405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697158.776405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697158.875405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '75' for key 'PRIMARY'")
[1499697159.3374052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697159.540405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697159.699405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697160.991405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '76' for key 'PRIMARY'")
[1499697161.156405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cardrecharge' at row 1")
[1499697161.724405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697162.716405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '77' for key 'PRIMARY'")
[1499697163.470405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cardrecharge' at row 1")
[1499697164.4074051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697165.220405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697165.300405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '82' for key 'PRIMARY'")
[1499697165.7384052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697165.843405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697165.9734051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697167.132405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '83' for key 'PRIMARY'")
[1499697167.8974051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697169.2944052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697169.427405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '88' for key 'PRIMARY'")
[1499697170.3544052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697170.548405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697170.790405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697172.175405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697172.274405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '89' for key 'PRIMARY'")
[1499697173.1534052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_avg_day_laundryroom' at row 1")
[1499697173.2574053]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'cost_rate_laundryroom' at row 1")
[1499697173.6144052]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697175.069405]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697175.432405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '92' for key 'PRIMARY'")
[1499697177.039405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697178.540405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '93' for key 'PRIMARY'")
[1499697180.900405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9054053]: 
            CostAmountCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9104052]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.915405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.919405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9264052]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9334052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.940405]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9434052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.948405]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.952405]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.959405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9624052]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9634051]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.964405]: 
            LibraryBorrowCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697180.9654052]: 
            LibraryTimesCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.399405]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.403405]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.403405]: 
            SubsidyCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.4074051]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.411405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.415405]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697181.415405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.592405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.605405]: 
            BalanceRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6144052]: 
            CardRechargeCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.618405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6294053]: 
            CostAmountCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6344051]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.638405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.643405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6494052]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.656405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.662405]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6674051]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6704051]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.675405]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6824052]: 
            CostVarianceCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6854053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.6864052]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.687405]: 
            LibraryBorrowCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697182.687405]: 
            LibraryTimesCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.0754051]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.080405]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.0814052]: 
            SubsidyCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.085405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.088405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.092405]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697183.0934052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.402405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4134052]: 
            BalanceRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.424405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.435405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4434052]: 
            CostAmountCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.448405]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.452405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.457405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4624052]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.468405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.474405]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4784052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4824052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.4864051]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.492405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.496405]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.508405]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.5094051]: 
            LibraryBorrowCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697184.510405]: 
            LibraryTimesCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.3734052]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.3774052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.378405]: 
            SubsidyCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.382405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.3864052]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.3894053]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697185.3904052]: 
        ScoreRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697186.937405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.013405]: 
            BalanceRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0224051]: 
            CardRechargeCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.031405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.040405]: 
            CostAmountCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.049405]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0544052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0574052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.062405]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.066405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0714052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0744052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0774052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.079405]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.084405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.087405]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.088405]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.088405]: 
            LibraryBorrowCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.0894053]: 
            LibraryTimesCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.4074051]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.4104052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.411405]: 
            SubsidyCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.414405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.4174051]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.420405]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697187.421405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampustrain.students' doesn't exist")
[1499697188.512405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697188.524405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697188.529405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697188.539405]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697188.5454051]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697188.556405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697188.569405]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697188.5714052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697188.5734053]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697188.5774052]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697188.579405]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697188.579405]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697188.902405]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697188.9054053]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697188.908405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697188.9104052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697191.408405]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697191.480405]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697191.493405]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697191.4984052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697191.5054052]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697191.510405]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697191.515405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697191.524405]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697191.5344052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697191.625405]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697191.640405]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697191.6464052]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697191.658405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697191.6664052]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697191.6674051]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697192.179405]: 
        ScoreRankCalculater
        	<class 'pymysql.err.IntegrityError'>:(1062, "Duplicate entry '6' for key 'PRIMARY'")
[1499697192.4254053]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697192.6504052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697192.664405]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697192.671405]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697193.340405]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697193.5654051]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampusvalidate.card_2' doesn't exist")
[1499697196.403405]: 
            SubsidyCalculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697196.408405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697198.0554051]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697198.1734052]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697198.1834052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697198.191405]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697198.200405]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697198.2094052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697198.214405]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697198.220405]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697198.224405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697198.2294052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697198.232405]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697198.235405]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697198.2384052]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697198.244405]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697198.247405]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697198.248405]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697198.898405]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697199.036405]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697199.0454051]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697199.0534053]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697209.407005]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697209.5172052]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697209.5328052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697209.5328052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697209.5328052]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697209.5484052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697209.5484052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697209.5640051]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697209.5640051]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697209.5796053]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697209.5796053]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697209.5796053]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697209.595205]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697209.6108053]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697209.6108053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697209.6108053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697210.1880052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697210.281605]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697210.2972052]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697210.3128052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697211.9362054]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697212.1244051]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampusvalidate.card_2' doesn't exist")
[1499697213.3724053]: 
            SubsidyCalculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697213.388005]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697219.240005]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697219.3190053]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697219.3346052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697219.3502052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697219.3658054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697219.3658054]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697219.3658054]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697219.381405]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697219.381405]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697219.381405]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697219.3970053]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697219.3970053]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697219.3970053]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697219.4126053]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697219.4126053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697219.4126053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697219.9274054]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697220.1146054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697220.1146054]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697220.1302052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697225.4352055]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697225.576605]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697225.5922053]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697225.5922053]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697225.6078053]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697225.6078053]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697225.6078053]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697225.6078053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697225.6078053]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697225.6234052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697225.6234052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697225.6234052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697225.6234052]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697225.6234052]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697225.6234052]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697225.6234052]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697226.6842053]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697226.9338052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697226.9338052]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697226.9494052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697237.3758051]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697237.7038052]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampusvalidate.card_2' doesn't exist")
[1499697238.2798052]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697238.4458053]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697238.4498053]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697238.4538052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697238.4578054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697238.4618053]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697238.4658053]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697238.4728053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697238.4798052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697238.4858053]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697238.4908051]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697238.4948053]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697238.4978054]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697238.5058053]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697238.5088053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697238.5098052]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697238.527805]: 
            SubsidyCalculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697238.5328054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'time6_7costs' at row 1")
[1499697240.803805]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697240.9088054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697240.9208055]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697240.9328053]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697245.0438051]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697245.1696055]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697245.1696055]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697245.1696055]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697245.1852052]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697245.1852052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697245.1852052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697245.2008054]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697245.2164052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697245.2164052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697245.2380052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697245.2440054]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697245.2490053]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697245.2600055]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697245.2620053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697245.2620053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697245.8274052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697245.8784053]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697245.8940053]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697245.9096053]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697248.6239052]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697248.7507055]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697248.7557054]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697248.7713053]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697248.7713053]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697248.7869053]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697248.7869053]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697248.7869053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697248.9429054]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697248.9429054]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697248.9585052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697248.9585052]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697248.9741054]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697248.9741054]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697248.9741054]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697249.5855052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697249.7415054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697249.7571054]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697249.7571054]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697249.8371055]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697249.9059055]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697249.9215052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697249.9215052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697249.9371054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697249.9371054]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697249.9371054]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697249.9547055]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697249.9703052]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697249.9703052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697249.9859054]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697249.9859054]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697250.0015054]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697250.0015054]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697250.0171053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697250.0171053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697250.5203054]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697250.6443055]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697250.6563053]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697250.6613054]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697250.843305]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697251.0683055]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697251.0773053]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697251.0833051]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697251.0903053]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697251.0963054]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697251.1023052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697251.1143053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697251.1253054]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697251.1353052]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697251.1413054]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697251.1453054]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697251.1453054]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697251.1609051]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697251.1609051]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697251.1609051]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697251.5317054]: 
        CostTimesDaySupermarketCalculater
        	<class 'TypeError'>:object of type 'NoneType' has no len()
[1499697251.8097053]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697251.8317053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.ProgrammingError'>:(1146, "Table 'intelligentcampusvalidate.card_2' doesn't exist")
[1499697251.8987055]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697251.913705]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697251.9197054]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697252.0539055]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697252.1485054]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697252.1485054]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697252.1485054]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697252.1485054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697252.1641052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697252.1641052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697252.1641052]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697252.1797054]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697252.1797054]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697252.1797054]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697252.1797054]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697252.195305]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697252.195305]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697252.195305]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697252.195305]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697252.3513052]: 
            LibraryTimeSpandCalculater
        	<class 'pymysql.err.DataError'>:(1265, "Data truncated for column 'library_time_spand' at row 1")
[1499697252.4413054]: 
            SubsidyCalculater
        	<class 'TypeError'>:'NoneType' object is not subscriptable
[1499697253.6457052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697253.7247052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697253.7423053]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697253.7473052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697253.9103053]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697254.0081053]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697254.0237052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697254.0237052]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697254.0237052]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697254.0393052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697254.0393052]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697254.0549054]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697254.0549054]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697254.0705051]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697254.0705051]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697254.0861053]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697254.0861053]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697254.1017053]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697254.1017053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697254.1017053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697254.7885053]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697254.9319053]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697254.9475055]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697254.9475055]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697255.0421054]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697255.0889053]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697255.1045053]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697255.1045053]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697255.1045053]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697255.1045053]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697255.1045053]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697255.1201053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697255.1201053]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697255.1201053]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697255.1357052]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697255.1357052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697255.1357052]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697255.1357052]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697255.1513052]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697255.1513052]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697255.8605053]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697255.8927052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697255.9083054]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697255.9083054]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697255.9863052]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697256.1111052]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697256.1267054]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697256.1267054]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697256.1423054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697256.1423054]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697256.1579053]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697256.1579053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697256.1579053]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697256.1735053]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697256.1735053]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697256.1735053]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697256.1735053]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697256.1891055]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697256.1891055]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697256.1891055]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697256.7463052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697256.8093054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697256.8123055]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697256.8153052]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697256.9923055]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697257.0863054]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697257.1023052]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697257.1073053]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697257.1143053]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697257.1183052]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697257.1223054]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697257.1313052]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697257.139305]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697257.1483054]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697257.1533053]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697257.1583052]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697257.1643054]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697257.1743052]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697257.1793053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697257.1793053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697258.7561052]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697259.3177052]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697259.3267055]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697259.3317053]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697259.5845053]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
[1499697259.8625052]: 
            CardRechargeCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cardrecharge' in 'field list'")
[1499697259.8715055]: 
            ConsumeTimes11_12Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes11_12' in 'field list'")
[1499697259.8795054]: 
            CostAmountCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_amount' at row 1")
[1499697259.8895054]: 
        CostAverageDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_dinnerhall' in 'field list'")
[1499697259.8955054]: 
        CostAverageDayLaundryRoomCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_LaundryRoom' in 'field list'")
[1499697259.8995054]: 
        CostAverageDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_avg_day_Supermarket' in 'field list'")
[1499697259.9045053]: 
        CostRateDinnerHallCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_dinnerhall' at row 1")
[1499697259.9095054]: 
        CostRateLaundryRoomCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_laundryroom' at row 1")
[1499697259.9135053]: 
        CostRateSupermarketCalculater
        	<class 'pymysql.err.DataError'>:(1406, "Data too long for column 'cost_rate_supermarket' at row 1")
[1499697259.9165053]: 
        CostTimesDayDinnerHallCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_dinnerhall' in 'field list'")
[1499697259.9195054]: 
        CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697259.9225051]: 
            CostTimesDaySupermarketCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_times_day_Supermarket' in 'field list'")
[1499697259.9275055]: 
            CostVarianceCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'cost_variance' in 'field list'")
[1499697259.9305053]: 
            CosumeTimes0_25Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'consumetimes0_25' in 'field list'")
[1499697259.9305053]: 
            CountCost0_10Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'countcost0_10' in 'field list'")
[1499697260.6755054]: 
            MaxCost7_8Calculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'maxcost7_8' in 'field list'")
[1499697260.7975054]: 
            Time6_7CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time6_7costs' in 'field list'")
[1499697260.8055053]: 
            Time7_8CostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'time7_8costs' in 'field list'")
[1499697260.8795054]: 
            TotalDinnerCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'totaldinnercosts' in 'field list'")
[1499697261.1385052]: 
            AvgDaysCostsCalculater
        	<class 'pymysql.err.InternalError'>:(1054, "Unknown column 'avgdayscosts' in 'field list'")
